[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions_ota_8mb.csv
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D AMAP_FIRMWARE_VERSION=\"0.1.0\"
  -D AMAP_FIRMWARE_BUILD=1
  -D AMAP_FIRMWARE_CHANNEL=\"dev\"
lib_deps =
  bblanchon/ArduinoJson
  olikraus/U8g2
